---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["apache2"]
    state: latest
    update_cache: yes

- name: Creates directory
  become: yes
  file:
    path: /var/www/html/
    state: directory

- name: Copy index test page
  become: yes  
  template:
    src: "files/index.html"
    dest: "/var/www/html/index.html"

# - name: Executing node
#   shell: |
#     pm2 start ~/web/index.js -f